export default {
    // LOGIN 
    GET_USER: 'GET_USER',
    GETTING_USER: 'GETTING_USER',
    // SISTEMA
    NAVIGATION: 'NAVIGATION',
    NEW: 'NEW',
    CLIENTE: 'CLIENTE',
    ALERTA: 'ALERTA',
    TYPE_ALERTA: 'TYPE_ALERTA',
    LOADING_SYSTEM: 'LOADING_SYSTEM',
    GET_SYSTEM: 'GET_SYSTEM',
    // EMBUDO
    LOADING_EMBUDO: 'LOADING_EMBUDO',
    GET_ITEM: 'GET_ITEM',
    GETTING_ITEM: 'GETTING_ITEM',
    GET_FUENTE: 'GET_FUENTE',
    GET_PROSPECTOS: 'GET_PROSPECTOS',
    GETTING_PROSPECTOS: 'GETTING_PROSPECTOS',
    GET_CONTACTOS: 'GET_CONTACTOS',
    GETTING_CONTACTOS: 'GETTING_CONTACTOS',
    GET_VISITAS: 'GET_VISITAS',
    GETTING_VISITAS: 'GETTING_VISITAS',
    GET_COTIZACIONES: 'GET_COTIZACIONES',
    GETTING_COTIZACIONES: 'GETTING_COTIZACIONES',
    GET_APROBADAS: 'GET_APROBADAS',
    GETTING_APROBADAS: 'GETTING_APROBADAS',
    GET_COTIZACION: 'GET_COTIZACION',
    GETTING_COTIZACION: 'GETTING_COTIZACION',

    GET_TIME: 'GET_TIME',
    // CALENDARIO
    GET_CALENDAR: 'GET_CALENDAR',
    GETTING_CALENDAR: 'GETTING_CALENDAR',
    GET_ITEM_CALENDAR: 'GET_ITEM_CALENDAR',

    // CLIENTS
    GET_CLIENT: 'GET_CLIENT',
    GETTING_CLIENT: 'GETTING_CLIENT',
    GET_TIME_CLIENT: 'GET_TIME_CLIENT',

    // ASESORES
    GETTING_ASESOR: 'GETTING_ASESOR',
    GET_ASESOR: 'GET_ASESOR',
    GET_ASESORES: 'GET_ASESORES',
    GETTING_ASESORES: 'GETTING_ASESORES',
     
    AVATARS: 'AVATARS',
    A: 'A'
}
